name: test

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *" # 每天的 0:00 执行
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config --local user.email "218928951+FranzPabst8@users.noreply.github.com" 
          git config --local user.name "FranzPabst8"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase

      - name: Random commit script
        run: |
          echo "cmFuZG9tX251bT0kKChSQU5ET00gJSA1ICsgMSkpCm49JCgoUkFORE9NICUgMyArIDEpKQp3YWl0X3RpbWU9JCgoUkFORE9NICUgMTYgKyA1KSkKZWNobyAi55Sf5oiQMeWIsDXnmoTpmo/mnLrmlbDvvIzlpoLmnpzmmK8x6L+95Yqg77yM55Sf5oiQMuimhueblu+8jOeUn+aIkOWFtuS7luaVsOWtl+S4jeaTjeS9nOOAguaPkOS6pOamgueOh+aYrzIvNSIKZWNobyAi6ZqP5py65pWwOiAkcmFuZG9tX251bSwg5b6q546vOiAkbiDmrKHvvIzmr4/mrKHlvqrnjq/nrYnlvoXml7bpl7TvvJokd2FpdF90aW1lIOenkiIKaWYgWyAkcmFuZG9tX251bSAtZXEgMSBdOyB0aGVuCiAgICBmb3IgaSBpbiAkKHNlcSAxICRuKTsgZG8KICAgICAgZWNobyAi56ysICRpIOasoeWGmeWFpe+8miIKICAgICAgZGF0ZSA+PiB0ZXN0LnR4dAogICAgICBnaXQgYWRkIC4gJiYgZ2l0IGNvbW1pdCAtbSAidXBkYXRlIiAmJiBnaXQgcHVzaAogICAgICBzbGVlcCAkd2FpdF90aW1lCiAgICBkb25lCiAgICBlY2hvICLov73liqDlhpnlhaXlhajpg6jlrozmiJDjgIIiCmVsaWYgWyAkcmFuZG9tX251bSAtZXEgMiBdOyB0aGVuCiAgICBmb3IgaSBpbiAkKHNlcSAxICRuKTsgZG8KICAgICAgZWNobyAi56ysICRpIOasoeWGmeWFpe+8miIKICAgICAgZGF0ZSA+IHRlc3QudHh0CiAgICAgIGdpdCBhZGQgLiAmJiBnaXQgY29tbWl0IC1tICJ1cGRhdGUiICYmIGdpdCBwdXNoCiAgICAgIHNsZWVwICR3YWl0X3RpbWUKICAgIGRvbmUKICAgIGVjaG8gIuimhuebluWGmeWFpeWFqOmDqOWujOaIkOOAgiIKZWxzZQogICAgZWNobyAi5pWw5a2X5pivICRyYW5kb21fbnVt77yM5LiN5omn6KGM5Lu75L2V5pON5L2cIgpmaQ==" | base64 -d | bash
# echo "" | base64 -d | bash
         
