name: test

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *" # 每天的 0:00 执行
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config --local user.email "218928951+FranzPabst8@users.noreply.github.com" 
          git config --local user.name "FranzPabst8"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase

      - name: Random commit script
        run: |
          echo "cmFuZG9tX251bT0kKChSQU5ET00gJSA1ICsgMSkpCm49JCgoUkFORE9NICUgMyArIDEpKQp3YWl0X3RpbWU9JCgoUkFORE9NICUgNjggKyA2MCkpCmVjaG8gIueUn+aIkDHliLA155qE6ZqP5py65pWw77yM5aaC5p6c5pivMei/veWKoO+8jOeUn+aIkDLopobnm5bvvIznlJ/miJDlhbbku5bmlbDlrZfkuI3mk43kvZzjgILmj5DkuqTmpoLnjofmmK8yLzUiCmVjaG8gIumaj+acuuaVsDogJHJhbmRvbV9udW0sIOW+queOrzogJG4g5qyh77yM5q+P5qyh5b6q546v562J5b6F5pe26Ze077yaJHdhaXRfdGltZSDnp5IiCmlmIFsgJHJhbmRvbV9udW0gLWVxIDEgXTsgdGhlbgogICAgZm9yIGkgaW4gJChzZXEgMSAkbik7IGRvCiAgICAgIGVjaG8gIuesrCAkaSDmrKHlhpnlhaXvvJoiCiAgICAgIGRhdGUgPj4gdGVzdC50eHQKICAgICAgZ2l0IGFkZCAuICYmIGdpdCBjb21taXQgLW0gInVwZGF0ZSIgJiYgZ2l0IHB1c2gKICAgICAgc2xlZXAgJHdhaXRfdGltZQogICAgZG9uZQogICAgZWNobyAi6L+95Yqg5YaZ5YWl5YWo6YOo5a6M5oiQ44CCIgplbGlmIFsgJHJhbmRvbV9udW0gLWVxIDIgXTsgdGhlbgogICAgZm9yIGkgaW4gJChzZXEgMSAkbik7IGRvCiAgICAgIGVjaG8gIuesrCAkaSDmrKHlhpnlhaXvvJoiCiAgICAgIGRhdGUgPiB0ZXN0LnR4dAogICAgICBnaXQgYWRkIC4gJiYgZ2l0IGNvbW1pdCAtbSAidXBkYXRlIiAmJiBnaXQgcHVzaAogICAgICBzbGVlcCAkd2FpdF90aW1lCiAgICBkb25lCiAgICBlY2hvICLopobnm5blhpnlhaXlhajpg6jlrozmiJDjgIIiCmVsc2UKICAgIGVjaG8gIuaVsOWtl+aYryAkcmFuZG9tX251be+8jOS4jeaJp+ihjOS7u+S9leaTjeS9nCIKZmk=" | base64 -d | bash
# echo "" | base64 -d | bash
         
