name: test

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *" # 每天的 0:00 执行
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config --local user.email "218928951+FranzPabst8@users.noreply.github.com" 
          git config --local user.name "FranzPabst8"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase

      - name: Random commit script
        run: |
          echo "cmFuZG9tX251bT0kKChSQU5ET00gJSA3ICsgMSkpCm49JCgoUkFORE9NICUgNSArIDEpKQplY2hvICLnlJ/miJAx5YiwN+eahOmaj+acuuaVsO+8jOWmguaenOaYrzHmiJYy6L+95Yqg77yM55Sf5oiQM+imhueblu+8jOeUn+aIkOWFtuS7luaVsOWtl+S4jeaTjeS9nOOAguaPkOS6pOamgueOh+aYrzMvNyIKZWNobyAi6ZqP5py65pWwOiAkcmFuZG9tX251bSwg5b6q546vOiAkbiDmrKEiCmlmIFsgJHJhbmRvbV9udW0gLWVxIDEgXSB8fCBbICRyYW5kb21fbnVtIC1lcSAyIF07IHRoZW4KICAgIGZvciAoKCBpPTE7IGk8PW47IGkrKyApKTsgZG8KICAgICAgZWNobyAi56ysICRpIOasoeWGmeWFpe+8miIKICAgICAgZGF0ZSA+PiB0ZXN0LnR4dAogICAgICBnaXQgYWRkIC4gJiYgZ2l0IGNvbW1pdCAtbSAidXBkYXRlIiAmJiBnaXQgcHVzaAogICAgICB0MT0kKChSQU5ET00gJSA4NiArIDEwKSkKICAgICAgc2xlZXAgJHQxCiAgICBkb25lCiAgICBlY2hvICLov73liqDlhpnlhaXlhajpg6jlrozmiJDjgIIiCmVsaWYgWyAkcmFuZG9tX251bSAtZXEgMyBdOyB0aGVuCiAgICBmb3IgKCggaT0xOyBpPD1uOyBpKysgKSk7IGRvCiAgICAgIGVjaG8gIuesrCAkaSDmrKHlhpnlhaXvvJoiCiAgICAgIGRhdGUgPiB0ZXN0LnR4dAogICAgICBnaXQgYWRkIC4gJiYgZ2l0IGNvbW1pdCAtbSAidXBkYXRlIiAmJiBnaXQgcHVzaAogICAgICB0Mj0kKChSQU5ET00gJSA2NiArIDEwKSkKICAgICAgc2xlZXAgJHQyCiAgICBkb25lCiAgICBlY2hvICLopobnm5blhpnlhaXlhajpg6jlrozmiJDjgIIiCmVsc2UKICAgIGVjaG8gIuaVsOWtl+aYryAkcmFuZG9tX251be+8jOS4jeaJp+ihjOS7u+S9leaTjeS9nCIKZmk=" | base64 -d | bash
# echo "" | base64 -d | bash
         
